import './styles.css';
import { createClient } from '@supabase/supabase-js';

const sbUrl=import.meta.env.VITE_SUPABASE_URL, sbKey=import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase=sbUrl&&sbKey?createClient(sbUrl,sbKey):null;
const demo={
  books:[
    {id:1,title:'الرحيق المختوم',author:'صفي الرحمن المباركفوري',summary:'بحث في السيرة النبوية على صاحبها أفضل الصلاة والسلام.',quantity:4,pages:520,cover:'c1'},
    {id:2,title:'لأنك الله',author:'علي بن جابر الفيفي',summary:'رحلة إلى السماء السابعة والتأمل في أسماء الله الحسنى.',quantity:2,pages:192,cover:'c2'},
    {id:3,title:'صور من حياة الصحابة',author:'عبد الرحمن رأفت الباشا',summary:'مواقف مضيئة من حياة أصحاب رسول الله.',quantity:6,pages:448,cover:'c3'},
    {id:4,title:'فاتتني صلاة',author:'إسلام جمال',summary:'كتاب يعين القارئ على المحافظة على الصلاة وحضور القلب.',quantity:1,pages:215,cover:'c4'},
    {id:5,title:'الداء والدواء',author:'ابن قيم الجوزية',summary:'جواب شاف لمن سأل عن الدواء النافع.',quantity:0,pages:384,cover:'c5'}
  ],
  profiles:[
    {id:'s1',name:'عبدالله محمد',role:'student',points:247,daily_target:15,books_count:2,pages_week:58},
    {id:'s2',name:'عمر خالد',role:'student',points:231,daily_target:12,books_count:1,pages_week:44},
    {id:'s3',name:'سلمان أحمد',role:'student',points:198,daily_target:10,books_count:2,pages_week:39},
    {id:'s4',name:'يوسف علي',role:'student',points:176,daily_target:10,books_count:1,pages_week:35}
  ],
  loans:[
    {id:1,student_id:'s1',book_id:1,pages_read:318,completed_at:null,returned_at:null},
    {id:2,student_id:'s1',book_id:2,pages_read:74,completed_at:null,returned_at:null},
    {id:3,student_id:'s1',book_id:3,pages_read:448,completed_at:'2026-08-13',returned_at:'2026-08-14'},
    {id:4,student_id:'s1',book_id:4,pages_read:215,completed_at:'2026-07-23',returned_at:'2026-07-24'}
  ],
  requests:[
    {id:1,student_id:'s1',book_id:3,note:'أرغب بقراءته ضمن خطة السيرة لهذا الشهر.',status:'pending',created_at:'2026-08-29'},
    {id:2,student_id:'s2',book_id:4,note:'اقترحه عليّ المشرف.',status:'pending',created_at:'2026-08-28'},
    {id:3,student_id:'s1',book_id:5,note:'أرغب بقراءته بعد إنهاء الكتاب الحالي.',status:'rejected',created_at:'2026-08-20'}
  ]
};
let state={user:null,role:null,page:'public',books:[],profiles:[],loans:[],requests:[],modal:null};
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function icon(name){return ({book:'▤',private:'▣',journey:'⌁',rank:'♛',request:'◷',menu:'☰',bell:'♢',plus:'＋'}[name]||'•')}

async function loadData(){
  if(!supabase){Object.assign(state,{books:demo.books,profiles:demo.profiles,loans:demo.loans,requests:demo.requests});return}
  const [b,p,l,r]=await Promise.all([supabase.from('books').select('*').order('created_at',{ascending:false}),supabase.from('profiles').select('*'),supabase.from('loans').select('*'),supabase.from('book_requests').select('*').order('created_at',{ascending:false})]);
  if(b.error) return toast('تعذر تحميل البيانات'); Object.assign(state,{books:b.data,profiles:p.data,loans:l.data,requests:r.data});
}
function loginView(){
  $('#app').innerHTML=`<main class="login-page"><section class="login-art"><div class="login-brand"><div class="brand-mark">۞</div><div><h1>مكتبة حلقة مسجد النملة</h1><small>نقرأ لنرتقي</small></div></div><div class="quote"><h2>خيرُ جليسٍ<br>في الزمانِ كتابُ</h2><p>منصة تجمع طلاب الحلقة بكتبهم، وتحوّل كل صفحة يقرؤونها إلى خطوة في طريق المعرفة.</p></div><small>حلقة مسجد النملة المسائية · جميع الحقوق محفوظة</small></section><section class="login-box"><form class="login-form" id="loginForm"><h2>مرحبًا بعودتك</h2><p>سجّل دخولك برقم الجوال للوصول إلى مكتبة الحلقة</p><div class="form"><div class="field"><label>رقم الجوال</label><input name="phone" type="tel" inputmode="tel" dir="ltr" placeholder="05xxxxxxxx" autocomplete="tel" required></div><div class="field"><label>كلمة المرور</label><input name="password" type="password" placeholder="••••••••" autocomplete="current-password" required></div><button class="btn">تسجيل الدخول</button></div></form></section></main>`;
  $('#loginForm').onsubmit=login;
}
function normalizePhone(value){const digits=String(value).replace(/\D/g,'');if(digits.startsWith('00966'))return `+${digits.slice(2)}`;if(digits.startsWith('966'))return `+${digits}`;if(digits.startsWith('05'))return `+966${digits.slice(1)}`;if(digits.startsWith('5'))return `+966${digits}`;return String(value).trim()}
async function login(e){e.preventDefault();if(!supabase)return toast('اربط Supabase أولًا، أو استخدم الدخول التجريبي');const fd=new FormData(e.currentTarget),phone=normalizePhone(fd.get('phone')),{data,error}=await supabase.auth.signInWithPassword({phone,password:fd.get('password')});if(error)return toast('رقم الجوال أو كلمة المرور غير صحيحة');const {data:profile,error:profileError}=await supabase.from('profiles').select('*').eq('id',data.user.id).single();if(profileError)return toast('تعذر تحميل الحساب');state.user=profile;state.role=profile.role;if(profile.must_change_password)return passwordChangeView();await loadData();render()}
function passwordChangeView(){
  $('#app').innerHTML=`<main class="login-page"><section class="login-art"><div class="login-brand"><div class="brand-mark">۞</div><div><h1>مكتبة حلقة مسجد النملة</h1><small>حماية حسابك أولًا</small></div></div><div class="quote"><h2>كلمة مرورك<br>مفتاح حسابك</h2><p>اختر كلمة لا يعرفها أحد غيرك، ولا تستخدم كلمة المرور المؤقتة مرة أخرى.</p></div><small>لن تتمكن من دخول المكتبة قبل إتمام هذه الخطوة</small></section><section class="login-box"><form class="login-form" id="passwordForm"><h2>أنشئ كلمة مرور جديدة</h2><p>هذا أول دخول لك، لذلك يجب تغيير كلمة المرور المؤقتة.</p><div class="notice">استخدم 8 أحرف على الأقل، ويفضل الجمع بين الحروف والأرقام.</div><div class="form"><div class="field"><label>كلمة المرور الجديدة</label><input name="password" type="password" minlength="8" autocomplete="new-password" required></div><div class="field"><label>تأكيد كلمة المرور</label><input name="confirm" type="password" minlength="8" autocomplete="new-password" required></div><button class="btn">حفظ ودخول المكتبة</button></div></form></section></main>`;
  $('#passwordForm').onsubmit=changeFirstPassword;
}
async function changeFirstPassword(e){e.preventDefault();const fd=new FormData(e.currentTarget),password=fd.get('password');if(password!==fd.get('confirm'))return toast('كلمتا المرور غير متطابقتين');if(password.length<8)return toast('كلمة المرور يجب ألا تقل عن 8 أحرف');const {error}=await supabase.auth.updateUser({password});if(error)return toast('تعذر تغيير كلمة المرور');const {error:flagError}=await supabase.rpc('mark_password_changed');if(flagError)return toast('تم تغيير الكلمة، لكن تعذر إكمال تهيئة الحساب');state.user.must_change_password=false;await loadData();toast('تم حفظ كلمة المرور الجديدة');render()}
function navItems(){const base=[['public','book','المكتبة العامة'],['leaderboard','rank','لوحة المتصدرين'],['requests','request','الطلبات']];if(state.role==='student')base.splice(1,0,['private','private','مكتبتي الخاصة'],['journey','journey','المسيرة']);return base}
function shell(){
  const pending=state.role==='admin'?state.requests.filter(r=>r.status==='pending').length:state.requests.filter(r=>r.student_id===state.user.id&&r.status==='pending').length;
  $('#app').innerHTML=`<div class="shell"><aside class="sidebar" id="sidebar"><div class="brand"><div class="brand-mark">۞</div><div><h1>مكتبة حلقة مسجد النملة</h1><span>نقرأ لنرتقي</span></div></div><nav class="nav">${navItems().map(([p,i,n])=>`<button data-page="${p}" class="${state.page===p?'active':''}"><span>${icon(i)}</span>${n}${p==='requests'&&pending?`<b class="count">${pending}</b>`:''}</button>`).join('')}</nav><div class="user-mini"><div class="avatar">${esc(state.user.name[0])}</div><div><strong>${esc(state.user.name)}</strong><small>${state.role==='admin'?'مشرف المكتبة':'طالب في الحلقة'}</small></div><button class="logout" title="تسجيل الخروج">↪</button></div></aside><main class="main"><div class="mobile-head"><b>مكتبة الحلقة</b><button id="menuBtn">☰</button></div><header class="topbar"><div><h2>${pageTitle()}</h2><p>${pageSubtitle()}</p></div><div class="top-actions"><button class="icon-btn">${icon('bell')}</button>${state.role==='admin'&&state.page==='public'?`<button class="btn" data-action="add-book">${icon('plus')} إضافة كتاب</button>`:''}</div></header><section id="content"></section></main></div>${modalView()}`;
  document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;state.modal=null;shell();renderPage()});$('.logout').onclick=async()=>{if(supabase)await supabase.auth.signOut();state={user:null,role:null,page:'public',books:[],profiles:[],loans:[],requests:[],modal:null};loginView()};$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');bindGlobal();renderPage();
}
function pageTitle(){return {public:'المكتبة العامة',private:'مكتبتي الخاصة',journey:'المسيرة',leaderboard:'لوحة المتصدرين',requests:'طلبات الكتب'}[state.page]}
function pageSubtitle(){return {public:'استكشف كتب الحلقة واختر قراءتك القادمة',private:'تابع تقدمك في الكتب الموجودة لديك',journey:'سجل إنجازاتك والكتب التي أتممت قراءتها',leaderboard:'تنافس في القراءة، وارتقِ كل أسبوع',requests:state.role==='admin'?'راجع طلبات الطلاب واتخذ القرار':'تابع حالة طلباتك السابقة'}[state.page]}
function render(){shell()}
function renderPage(){const c=$('#content');if(state.page==='public')c.innerHTML=publicView();if(state.page==='private')c.innerHTML=privateView();if(state.page==='journey')c.innerHTML=journeyView();if(state.page==='leaderboard')c.innerHTML=leaderboardView();if(state.page==='requests')c.innerHTML=requestsView();bindPage()}
function publicView(){const total=state.books.reduce((s,b)=>s+b.quantity,0);return `<div class="hero"><div><h3>أهلاً بك، ${esc(state.user.name.split(' ')[0])} 👋</h3><p>${state.role==='admin'?'أدر كتب الحلقة وتابع حركة الاستعارة من مكان واحد.':'كل صفحة تقرؤها اليوم، تبني بها مستقبلك غدًا.'}</p></div><div class="hero-stats"><div class="hero-stat"><strong>${state.books.length}</strong><span>عنوانًا</span></div><div class="hero-stat"><strong>${total}</strong><span>نسخة متاحة</span></div>${state.role==='student'?`<div class="hero-stat"><strong>${state.user.points}</strong><span>نقطة</span></div>`:''}</div></div><div class="section-head"><div><h3>كتب الحلقة</h3><p>مجموعة مختارة بعناية لطلابنا</p></div>${state.role==='admin'?`<button class="btn" data-action="add-book">＋ إضافة كتاب جديد</button>`:''}</div><div class="books-grid">${state.books.map(bookCard).join('')}</div>`}
function bookCard(b){return `<article class="book-card"><div class="cover ${b.cover||'c2'}"><span>${esc(b.title)}</span></div><div class="book-info"><h4>${esc(b.title)}</h4><p>${esc(b.author)} · ${esc(b.summary)}</p><div class="book-foot"><span class="stock ${b.quantity?'':'out'}">${b.quantity?`${b.quantity} نسخ متاحة`:'غير متوفر'}</span>${state.role==='student'?`<button class="link-btn" data-request="${b.id}" ${!b.quantity?'disabled':''}>اطلب الكتاب ←</button>`:`<button class="link-btn" data-edit-book="${b.id}">تعديل</button>`}</div></div></article>`}
function privateView(){const loans=state.loans.filter(l=>l.student_id===state.user.id&&!l.returned_at);return `<div class="stats-grid"><div class="stat-card"><span>الكتب لديك</span><strong>${loans.length} / 3</strong><em>يمكنك امتلاك ${3-loans.length} كتب أخرى</em></div><div class="stat-card"><span>صفحات هذا الأسبوع</span><strong>${state.user.pages_week||0}</strong><em>الهدف اليومي: ${state.user.daily_target} صفحة</em></div><div class="stat-card"><span>مجموع النقاط</span><strong>${state.user.points}</strong><em>نقطة لكل صفحة كل أربعاء</em></div></div><div class="section-head"><div><h3>كتبي الورقية</h3><p>سجّل ما قرأته من نسختك الورقية</p></div></div>${loans.length?`<div class="books-grid">${loans.map(l=>{const b=state.books.find(x=>x.id==l.book_id),pct=Math.min(100,Math.round(l.pages_read/(b.pages||400)*100));return `<article class="book-card"><div class="cover ${b.cover||'c2'}"><span>${esc(b.title)}</span></div><div class="book-info"><h4>${esc(b.title)}</h4><p>${l.pages_read} من ${b.pages||'—'} صفحة</p><div class="progress-row"><div class="progress"><i style="width:${pct}%"></i></div><small>${pct}%</small></div><button class="btn ghost" style="width:100%;margin-top:12px" data-progress="${l.id}">تسجيل القراءة</button></div></article>`}).join('')}</div>`:`<div class="panel empty">▣<b>مكتبتك فارغة حاليًا</b>اطلب كتابًا من المكتبة العامة</div>`}`}
function journeyView(){const finished=state.loans.filter(l=>l.student_id===state.user.id&&l.completed_at).sort((a,b)=>new Date(b.completed_at)-new Date(a.completed_at)),pages=finished.reduce((sum,l)=>sum+(state.books.find(b=>b.id==l.book_id)?.pages||l.pages_read),0);return `<div class="hero"><div><h3>مسيرتك مع القراءة</h3><p>كل كتاب أنهيته شاهدٌ على رحلة جميلة من العلم والمعرفة.</p></div><div class="hero-stats"><div class="hero-stat"><strong>${finished.length}</strong><span>كتب مكتملة</span></div><div class="hero-stat"><strong>${pages}</strong><span>صفحة منجزة</span></div></div></div><div class="section-head"><div><h3>الكتب التي قرأتها</h3><p>يُضاف الكتاب تلقائيًا عند تسجيل آخر صفحة فيه</p></div></div>${finished.length?`<div class="books-grid">${finished.map(l=>{const b=state.books.find(x=>x.id==l.book_id);return `<article class="book-card"><div class="cover ${b?.cover||'c2'}"><span>${esc(b?.title||'كتاب')}</span></div><div class="book-info"><h4>${esc(b?.title||'كتاب')}</h4><p>${esc(b?.author||'')} · ${b?.pages||l.pages_read} صفحة</p><div class="book-foot"><span class="status approved">✓ تمت القراءة</span><small>${new Date(l.completed_at).toLocaleDateString('ar-SA')}</small></div></div></article>`}).join('')}</div>`:`<div class="panel empty">⌁<b>ستبدأ مسيرتك من هنا</b>أكمل قراءة كتابك الأول ليظهر في هذه الصفحة</div>`}`}
function leaderboardView(){const ps=[...state.profiles].filter(p=>p.role==='student').sort((a,b)=>b.points-a.points);return `<div class="hero"><div><h3>فرسان القراءة</h3><p>تُحتسب نقطة لكل صفحة، ويتم تحديث الترتيب كل يوم أربعاء.</p></div><div class="hero-stats"><div class="hero-stat"><strong>${ps.reduce((s,p)=>s+p.points,0)}</strong><span>صفحة مقروءة</span></div></div></div><div class="section-head"><div><h3>ترتيب هذا الأسبوع</h3><p>استمر في القراءة لتصل إلى الصدارة</p></div></div><div class="table-wrap"><table class="table"><thead><tr><th>الترتيب</th><th>الطالب</th><th>صفحات الأسبوع</th><th>الهدف اليومي</th><th>النقاط</th>${state.role==='admin'?'<th>التحكم</th>':''}</tr></thead><tbody>${ps.map((p,i)=>`<tr><td><span class="rank ${i<3?'top':''}">${i+1}</span></td><td><div class="student-cell"><div class="avatar">${esc(p.name[0])}</div><b>${esc(p.name)}</b></div></td><td>${p.pages_week||0} صفحة</td><td>${p.daily_target} صفحة</td><td><b>${p.points}</b> نقطة</td>${state.role==='admin'?`<td><div class="actions"><button class="btn ghost" data-adjust="${p.id}" data-delta="-1">−</button><button class="btn" data-adjust="${p.id}" data-delta="1">＋</button><button class="link-btn" data-target="${p.id}">تعديل الهدف</button><button class="link-btn" data-library="${p.id}">مكتبته</button></div></td>`:''}</tr>`).join('')}</tbody></table></div>`}
function requestsView(){const rs=state.role==='admin'?state.requests:state.requests.filter(r=>r.student_id===state.user.id);const label={pending:'قيد المعالجة',approved:'مقبول',rejected:'مرفوض'};return `${state.role==='student'&&state.loans.filter(l=>l.student_id===state.user.id&&!l.returned_at).length>=3?'<div class="notice">لديك 3 كتب حاليًا، لذلك لا يمكنك طلب كتاب إضافي حتى تعيد أحدها.</div>':''}<div class="table-wrap"><table class="table"><thead><tr><th>الكتاب</th>${state.role==='admin'?'<th>الطالب</th>':''}<th>الملاحظة</th><th>التاريخ</th><th>الحالة</th>${state.role==='admin'?'<th>الإجراء</th>':''}</tr></thead><tbody>${rs.length?rs.map(r=>{const b=state.books.find(x=>x.id==r.book_id),p=state.profiles.find(x=>x.id===r.student_id);return `<tr><td><b>${esc(b?.title||'كتاب محذوف')}</b></td>${state.role==='admin'?`<td>${esc(p?.name||'طالب')}</td>`:''}<td>${esc(r.note||'—')}</td><td>${new Date(r.created_at).toLocaleDateString('ar-SA')}</td><td><span class="status ${r.status}">${label[r.status]}</span></td>${state.role==='admin'?`<td>${r.status==='pending'?`<div class="actions"><button class="btn" data-decide="${r.id}" data-status="approved">قبول</button><button class="btn danger" data-decide="${r.id}" data-status="rejected">رفض</button></div>`:'—'}</td>`:''}</tr>`}).join(''):`<tr><td colspan="6" class="empty">لا توجد طلبات بعد</td></tr>`}</tbody></table></div>`}
function modalView(){if(!state.modal)return '';const m=state.modal;if(m.type==='request'){const b=state.books.find(x=>x.id==m.id);return modal(`طلب كتاب: ${esc(b.title)}`,'سيصل طلبك إلى المشرف للمراجعة.',`<input type="hidden" name="book_id" value="${b.id}"><div class="field"><label>ملاحظة للمشرف</label><textarea name="note" placeholder="لماذا ترغب في قراءة هذا الكتاب؟" required></textarea></div>`,'إرسال الطلب')};if(m.type==='progress'){const l=state.loans.find(x=>x.id==m.id),b=state.books.find(x=>x.id==l.book_id);return modal('تسجيل القراءة',`سجّل عدد الصفحات التي وصلت إليها في «${esc(b.title)}».`,`<input type="hidden" name="loan_id" value="${l.id}"><div class="field"><label>وصلت إلى الصفحة</label><input type="number" name="pages" min="${l.pages_read}" max="${b.pages||9999}" value="${l.pages_read}" required></div>`,'حفظ التقدم')};if(m.type==='book'){const b=state.books.find(x=>x.id==m.id)||{};return modal(b.id?'تعديل الكتاب':'إضافة كتاب جديد','أدخل بيانات النسخة الورقية المتوفرة للطلاب.',`<input type="hidden" name="id" value="${b.id||''}"><div class="field"><label>عنوان الكتاب</label><input name="title" value="${esc(b.title||'')}" required></div><div class="form-row"><div class="field"><label>المؤلف</label><input name="author" value="${esc(b.author||'')}" required></div><div class="field"><label>عدد الصفحات</label><input name="pages" type="number" min="1" value="${b.pages||''}" required></div></div><div class="field"><label>نبذة</label><textarea name="summary" required>${esc(b.summary||'')}</textarea></div><div class="field"><label>عدد النسخ المتوفرة</label><input name="quantity" type="number" min="0" value="${b.quantity??1}" required></div>`,'حفظ الكتاب')};if(m.type==='target'){const p=state.profiles.find(x=>x.id===m.id);return modal('تعديل الهدف اليومي',`حدد عدد الصفحات اليومية المطلوبة من ${esc(p.name)}.`,`<input type="hidden" name="student_id" value="${p.id}"><div class="field"><label>عدد الصفحات يوميًا</label><input name="target" type="number" min="1" max="200" value="${p.daily_target}" required></div>`,'حفظ الهدف')};if(m.type==='library'){const p=state.profiles.find(x=>x.id===m.id),ls=state.loans.filter(x=>x.student_id===p.id);return `<div class="modal-backdrop"><div class="modal"><h3>مكتبة ${esc(p.name)}</h3><p>${ls.length} من 3 كتب بحوزته</p><div class="form">${ls.length?ls.map(l=>{const b=state.books.find(x=>x.id==l.book_id);return `<div class="panel"><b>${esc(b.title)}</b><p>${l.pages_read} صفحة مقروءة</p></div>`}).join(''):'<div class="empty">لا توجد كتب</div>'}<button class="btn ghost" data-close>إغلاق</button></div></div></div>`}return ''}
function modal(title,desc,fields,submit){return `<div class="modal-backdrop"><form class="modal" id="modalForm"><h3>${title}</h3><p>${desc}</p><div class="form">${fields}<div class="modal-actions"><button type="button" class="btn ghost" data-close>إلغاء</button><button class="btn">${submit}</button></div></div></form></div>`}
function bindGlobal(){document.querySelectorAll('[data-action="add-book"]').forEach(b=>b.onclick=()=>openModal('book'));document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeModal);const form=$('#modalForm');if(form)form.onsubmit=submitModal;const bg=$('.modal-backdrop');if(bg)bg.onclick=e=>{if(e.target===bg)closeModal()}}
function bindPage(){document.querySelectorAll('[data-request]').forEach(b=>b.onclick=()=>requestBook(Number(b.dataset.request)));document.querySelectorAll('[data-progress]').forEach(b=>b.onclick=()=>openModal('progress',Number(b.dataset.progress)));document.querySelectorAll('[data-edit-book]').forEach(b=>b.onclick=()=>openModal('book',Number(b.dataset.editBook)));document.querySelectorAll('[data-adjust]').forEach(b=>b.onclick=()=>adjustPoints(b.dataset.adjust,Number(b.dataset.delta)));document.querySelectorAll('[data-target]').forEach(b=>b.onclick=()=>openModal('target',b.dataset.target));document.querySelectorAll('[data-library]').forEach(b=>b.onclick=()=>openModal('library',b.dataset.library));document.querySelectorAll('[data-decide]').forEach(b=>b.onclick=()=>decide(Number(b.dataset.decide),b.dataset.status));document.querySelectorAll('[data-action="add-book"]').forEach(b=>b.onclick=()=>openModal('book'))}
function openModal(type,id){state.modal={type,id};shell()}function closeModal(){state.modal=null;shell()}
function requestBook(id){const owned=state.loans.filter(l=>l.student_id===state.user.id&&!l.returned_at).length;if(owned>=3)return toast('لا يمكنك طلب أكثر من 3 كتب');if(state.requests.some(r=>r.student_id===state.user.id&&r.book_id==id&&r.status==='pending'))return toast('لديك طلب قائم لهذا الكتاب');openModal('request',id)}
async function submitModal(e){e.preventDefault();const fd=new FormData(e.currentTarget),type=state.modal.type;if(type==='request'){const row={student_id:state.user.id,book_id:Number(fd.get('book_id')),note:fd.get('note'),status:'pending',created_at:new Date().toISOString()};if(supabase){const {data,error}=await supabase.from('book_requests').insert(row).select().single();if(error)return toast(error.message);state.requests.unshift(data)}else{row.id=Date.now();state.requests.unshift(row)}toast('تم إرسال طلبك للمشرف')}if(type==='progress'){const id=Number(fd.get('loan_id')),pages=Number(fd.get('pages')),l=state.loans.find(x=>x.id===id),delta=pages-l.pages_read,b=state.books.find(x=>x.id==l.book_id);if(supabase){const {error}=await supabase.rpc('record_reading_progress',{loan_id:id,new_page:pages});if(error)return toast(error.message)}l.pages_read=pages;if(pages===b.pages&&!l.completed_at)l.completed_at=new Date().toISOString();state.user.pages_week=(state.user.pages_week||0)+delta;const profile=state.profiles.find(x=>x.id===state.user.id);if(profile)profile.pages_week=state.user.pages_week;toast(pages===b.pages?'مبارك! أُضيف الكتاب إلى مسيرتك':'تم تحديث تقدمك')}if(type==='book'){const id=Number(fd.get('id')),row={title:fd.get('title'),author:fd.get('author'),summary:fd.get('summary'),pages:Number(fd.get('pages')),quantity:Number(fd.get('quantity')),cover:'c'+(state.books.length%5+1)};if(supabase){const q=id?supabase.from('books').update(row).eq('id',id).select().single():supabase.from('books').insert(row).select().single(),{data,error}=await q;if(error)return toast(error.message);id?Object.assign(state.books.find(x=>x.id===id),data):state.books.unshift(data)}else{id?Object.assign(state.books.find(x=>x.id===id),row):state.books.unshift({...row,id:Date.now()})}toast('تم حفظ الكتاب')}if(type==='target'){const id=fd.get('student_id'),v=Number(fd.get('target'));if(supabase){const {error}=await supabase.from('profiles').update({daily_target:v}).eq('id',id);if(error)return toast(error.message)}state.profiles.find(x=>x.id===id).daily_target=v;toast('تم تحديث الهدف اليومي')}state.modal=null;shell()}
async function adjustPoints(id,delta){const p=state.profiles.find(x=>x.id===id),v=Math.max(0,p.points+delta);if(supabase){const {error}=await supabase.from('profiles').update({points:v}).eq('id',id);if(error)return toast(error.message)}p.points=v;renderPage()}
async function decide(id,status){const r=state.requests.find(x=>x.id===id),book=state.books.find(x=>x.id==r.book_id);if(status==='approved'&&book.quantity<1)return toast('لا توجد نسخة متاحة');if(supabase){const {error}=await supabase.rpc('decide_book_request',{request_id:id,new_status:status});if(error)return toast(error.message);await loadData()}else{r.status=status;if(status==='approved'){book.quantity--;state.loans.push({id:Date.now(),student_id:r.student_id,book_id:r.book_id,pages_read:0});const p=state.profiles.find(x=>x.id===r.student_id);p.books_count=(p.books_count||0)+1}}toast(status==='approved'?'تم قبول الطلب وتسليم الكتاب':'تم رفض الطلب');renderPage()}

async function boot(){if(supabase){const {data:{session}}=await supabase.auth.getSession();if(session){const {data:p}=await supabase.from('profiles').select('*').eq('id',session.user.id).single();if(p){state.user=p;state.role=p.role;if(p.must_change_password)return passwordChangeView();await loadData();return render()}}}loginView()}
boot();
